export async function onRequestPost(context) {
    const { request } = context;
    
    const headers = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST,OPTIONS',
        'Content-Type': 'application/json'
    };

    try {
        const body = await request.json();
        const { name, email, phone, ageGroup, position, capability } = body;

        // Structured aesthetic email template optimized for Gmail preview layouts
        const emailHTMLContent = `
        <div style="background-color: #f3f4f6; padding: 30px; font-family: sans-serif;">
            <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; border-top: 6px solid #059669; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); padding: 25px;">
                <h2 style="color: #065f46; margin-top: 0; font-family: serif; text-transform: uppercase; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">🕊️ NAYI SUBAH APPLICATION INTERCEPT</h2>
                
                <p style="font-size: 14px; color: #4b5563;">A new candidate application file has been filed online via the LGS JT youth leadership portal node.</p>
                
                <div style="background-color: #f0fdf4; border-left: 4px solid #10b981; padding: 15px; margin: 20px 0; border-radius: 4px;">
                    <h3 style="margin: 0 0 10px 0; color: #065f46; font-size: 15px;">👤 CANDIDATE PROFILE</h3>
                    <p style="margin: 4px 0; font-size: 14px;"><strong>Full Name:</strong> ${name}</p>
                    <p style="margin: 4px 0; font-size: 14px;"><strong>Email Node:</strong> ${email}</p>
                    <p style="margin: 4px 0; font-size: 14px;"><strong>WhatsApp Line:</strong> ${phone}</p>
                    <p style="margin: 4px 0; font-size: 14px;"><strong>Age Classification:</strong> ${ageGroup}</p>
                </div>

                <div style="margin: 20px 0;">
                    <p style="margin: 4px 0; font-size: 14px;"><strong>Requested Position Node:</strong></p>
                    <div style="background-color: #fffbeb; border: 1px solid #fef3c7; color: #b45309; font-weight: bold; padding: 10px; border-radius: 6px; display: inline-block; font-size: 14px;">
                        🎯 ${position}
                    </div>
                </div>

                <div style="background-color: #f9fafb; border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px;">
                    <h4 style="margin: 0 0 8px 0; color: #374151; font-size: 13px; text-transform: uppercase; tracking: 1px;">Capabilities & Motivation Statement:</h4>
                    <p style="margin: 0; font-size: 13px; color: #4b5563; line-height: 1.6; font-style: italic;">"${capability}"</p>
                </div>

                <p style="font-size: 11px; color: #9ca3af; text-align: center; margin-top: 30px; border-top: 1px solid #f3f4f6; pt: 10px;">
                    Audit log generated by Nayi Subah Foundation Core Architecture. Review credentials and arrange validation interviews.
                </p>
            </div>
        </div>`;

        // Grab your secure Resend Key from your resend dashboard account (as done in previous task)
        const resendApiKey = 'YOUR_ACTUAL_RESEND_KEY_HERE';

        await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: { 
                'Authorization': `Bearer ${resendApiKey}`, 
                'Content-Type': 'application/json' 
            },
            body: JSON.stringify({
                from: 'NayiSubah Portal <onboarding@resend.dev>',
                to: 'sherazsubhan961@gmail.com', // Sends directly to your inbox for interview tracking
                subject: `🕊️ NEW CANDIDATE APPLICATION: ${name} [${position}]`,
                html: emailHTMLContent
            })
        });

        return new Response(JSON.stringify({ success: true }), { status: 200, headers });
    } catch (error) {
        return new Response(JSON.stringify({ success: false, error: error.toString() }), { status: 500, headers });
    }
}

export async function onRequestOptions() {
    return new Response(null, {
        status: 204,
        headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Headers': 'Content-Type',
            'Access-Control-Allow-Methods': 'POST,OPTIONS'
        }
    });
}
